const router = require('express').Router();
const main = require('../controllers/mainController');
router.get('/', main.home);
router.get('/about', main.about);
router.get('/contact', main.contact);
router.post('/contact', main.saveContact);
router.get('/admin', main.admin);
const games = require('../controllers/gameController');
router.get('/games', games.index);
router.post('/games', games.create);
module.exports = router;
